"""Self-documenting event type constants for chess game communication."""

# Chess piece movement and interaction events
PIECE_COMPLETED_SUCCESSFUL_MOVEMENT = "MOVE_DONE"
ENEMY_PIECE_CAPTURED_BY_PLAYER = "PIECE_CAPTURED"
PAWN_REACHED_PROMOTION_SQUARE = "PAWN_PROMOTION"
PLAYER_ATTEMPTED_INVALID_MOVE = "INVALID_MOVE"

# Game state management events  
CHESS_GAME_SESSION_STARTED = "GAME_STARTED"
CHESS_GAME_SESSION_ENDED = "GAME_ENDED"

# Backward compatibility aliases
MOVE_DONE = PIECE_COMPLETED_SUCCESSFUL_MOVEMENT
PIECE_CAPTURED = ENEMY_PIECE_CAPTURED_BY_PLAYER
GAME_STARTED = CHESS_GAME_SESSION_STARTED
GAME_ENDED = CHESS_GAME_SESSION_ENDED
INVALID_MOVE = PLAYER_ATTEMPTED_INVALID_MOVE
PAWN_PROMOTION = PAWN_REACHED_PROMOTION_SQUARE
